### ISSUE TITLE
this app is usless

### ISSUE THREAD

**Issue by JameIsEpic** [NanderTGA/generator-w-96#1]
this app is useless because it is a app generator, these are lazy and require no work, i will be seeing you in court shortly.

**Comment by NanderTGA** [comment]
This is supposed to include some tools when I actually write them, and not meant for easily making iframe apps and such. So this is not lazy, there a lot of generators like this to generate empty projects, so you don't need to do a lot of manual work.
Look up more projects that have a name starting with generator, most of these are yeoman (a command line tool) generators (there even is a generator-generator!) or similar things, such as npm init and eslint init.

**This comment is not meant to restart drama, but to make you aware of similar useful things like this.**
